### ISSUE TITLE
Option to appear at the top of the screen

### ISSUE THREAD

**Issue by spinda** [michalleptuch/battery-flyout#3]
Hi! This is a lovely little app. I use [StartAllBack](https://www.startallback.com/) to move my taskbar to the top of the screen, and it works just fine with Battery Flyout, except that the flyout appears at the bottom-right corner of my screen instead of the top-right where the tray is, so I have to move my mouse all the way down after summoning it. Could opening from the top be introduced as an option?

**Comment by spinda** [comment]
An illustration of the problem:

![Screenshot 2024-12-16 231516](https://github.com/user-attachments/assets/885a4da7-bea6-4b1c-86b5-06e51944ed62)

**Comment by michalleptuch** [comment]
This will be published after January 1st.

**Comment by michalleptuch** [comment]
This will be published after 11th of February. I need to wait for .NET 9.0.2 to fix some problems.

**Comment by spinda** [comment]
Thanks a ton for this!
